ARG LAVA_ARCH=amd64
FROM registry.gitlab.com/lava/lava/${LAVA_ARCH}/lava-dispatcher:2026.05.dev0091
ARG HOST_ARCH=amd64
ARG EXTRA_PACKAGES

RUN echo 'Acquire::Retries "3";' > /etc/apt/apt.conf.d/80-retries

RUN apt-get update && \
    apt-get install --no-install-recommends --yes gnupg && \
    apt-get install --yes libgpgme11-dev podman ${EXTRA_PACKAGES} && \
    mv /usr/bin/run-parts /usr/bin/run-parts.real && \
    echo '#!/bin/sh\nexit 0' > /usr/bin/run-parts && \
    chmod +x /usr/bin/run-parts && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes linux-image-cloud-${HOST_ARCH} && \
    mv /usr/bin/run-parts.real /usr/bin/run-parts && \
    echo "deb     http://ftp.de.debian.org/debian/    testing main contrib non-free" > /etc/apt/sources.list.d/testing.list && \
    echo "deb-src http://ftp.de.debian.org/debian/    testing main contrib non-free" >> /etc/apt/sources.list.d/testing.list && \
    apt-get update && \
    apt-get -t testing install --no-install-recommends --yes qemu-system-arm qemu-system-mips qemu-system-misc qemu-system-ppc qemu-system-riscv qemu-system-s390x qemu-system-sparc qemu-system-x86 && \
    apt-get upgrade --yes && \
    apt-get purge --yes gnupg && \
    apt-mark manual qemu-system-arm qemu-system-mips qemu-system-misc qemu-system-ppc qemu-system-riscv qemu-system-s390x qemu-system-sparc qemu-system-x86 && \
    apt-get autoremove --purge --yes && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Debian testing's containers-storage does not ship /etc/containers/storage.conf
# any more, and podman has no built-in fallback for these values. Without the
# file podman fails with "runroot must be set".
RUN { echo "[storage]"; \
      echo 'driver = "overlay"'; \
      echo 'runroot = "/run/containers/storage"'; \
      echo 'graphroot = "/var/lib/containers/storage"'; } > /etc/containers/storage.conf

COPY . /tuxrun/
RUN cd /tuxrun && pip3 install --break-system-packages . && \
    cd - && rm -rf /tuxrun
RUN podman --version && tuxrun --version

ENTRYPOINT ["/root/entrypoint.sh"]

# FIXME: Ugly hack to launch the http server here. This needs to be changed to use tuxmake runtime where we can run multiple commands. The launch of http server was tested with podman run command but that did not pass the sigkill correctly to lava-run.
RUN sed -i "s|set -e|set -e \npython3 -m http.server 80 -d /var/lib/lava/dispatcher/ \&|g" /root/entrypoint.sh ; cat /root/entrypoint.sh

# vim: ft=dockerfile
