FROM debian:bookworm

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install --no-install-recommends --yes ca-certificates curl gnupg && \
    apt-get update && \
    apt-get install --yes podman && \
    apt-get install --yes python3-jinja2 python3-requests python3-yaml linux-image-amd64 && \
    rm /usr/sbin/iptables && \
    ln -s /usr/sbin/iptables-legacy /usr/sbin/iptables && \
    apt-get purge --yes gnupg && \
    apt-get autoremove --purge --yes && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY share/pind/containers.conf /etc/containers/containers.conf

RUN \
    mkdir -p /var/lib/shared/overlay-images && \
    mkdir -p /var/lib/shared/overlay-layers && \
    mkdir -p /var/lib/shared/vfs-images && \
    mkdir -p /var/lib/shared/vfs-layers && \
    touch /var/lib/shared/overlay-images/images.lock && \
    touch /var/lib/shared/overlay-layers/layers.lock && \
    touch /var/lib/shared/vfs-images/images.lock && \
    touch /var/lib/shared/vfs-layers/layers.lock

# vim: ft=dockerfile
